### PR TITLE
Add js tutor to resources page

### PR DESCRIPTION
**Pull request by nigef**

### CODE REVIEW

**Comment by arkon** [comment]
This seems to include the changes from #25, but it seems fine.

**Comment by nigef** [comment]
Oops, I forget what happens if this doesn't have the changes from #25 and it gets merged after, does it try to delete the changes in #25 that aren't in #26?

**Comment by arkon** [comment]
I think it's fine if you do #25 then #26. Alternatively, you can just merge #26 and close #25.

**Comment by nigef** [comment]
reminder that i dont have merge permissions

**Pull request merged**
